S := R

R := ( R )
R := R [ B ]
R := R { Q }
R := R | R
R := R \ e
R := R *
R := R ?
R := R +
R := R .
R := R Σ
R := ε

B := ^ O
B := O

O := O \ e
O := O Σ - Σ
O := O Σ
O := ε

n := [1-9]
d := [0-9]

Q := N
Q := , N
Q := N ,
Q := N , N

N := n D
D := d D
D := ε

e := d
e := D
e := s
e := S
e := w
e := W
e := (
e := )
e := [
e := ]
e := {
e := }
e := |
e := \
e := *
e := ?
e := +
e := .
e := -
e := $
e := r
e := n
e := t
e := 0
